### PR TITLE
nuked SARSOP_jll

### PR DESCRIPTION
**Pull request by zsunberg**
I guess the way to solve the version conflict with General is just to completely remove SARSOP_jll here.

### CODE REVIEW

**Comment by rejuvyesh** [comment]
Hmm. This might affect previous versions of SARSOP depending on how it's registered on Yggdrasil/General. Main problem seems to be not using stricter version bounds. But we can just change that even now? We could also release another minor version of older SARSOP with updated version requirements for SARSOP_jll.

@MaximeBouton What versions are being assigned to the General one?

**Comment by MaximeBouton** [comment]
The version of SARSOP_jll is the same, there has been only one version of this package as far as I know. 
Older SARSOP should work with the _jll that is from general so I would think what @rejuvyesh suggested is a good idea: 
Tag a minor version of older SARSOP with the new SARSOP_jll from general instead and delete SARSOP_jll from this registry. How does that sound?

**Comment by rejuvyesh** [comment]
Oh wait. Looks like the issue is that they both have the same version numbers? Maybe then just nuking this is enough and we don't need a minor version release.

**Comment by zsunberg** [comment]
No need to tag a new version of SARSOP - it will work with the SARSOP_jll in General.

Since we agree that SARSOP_jll can be deleted from this registry, I am going to merge this tomorrow unless there are any objections.

**Comment by MaximeBouton** [comment]
will it really work? 
Are the UUIDs the same? I am guessing it is looking for the UUID that is in the Project.toml no?

**Comment by zsunberg** [comment]
Yes, the UUIDs are the same - it is just the git tree hashes for v0.96.0+0 that do not match

**Comment by zsunberg** [comment]
Ok, installing SARSOP with both registries works successfully now!

**Comment by rejuvyesh** [comment]
I think the issue will be if someone tries to use an older Manifest.toml

**Comment by zsunberg** [comment]
Ah, yeah, possibly, though I think the manifest toml stores the github information directly and therefore might not even rely on any registry, so it might just work. In any case, it should not be too terrible to recover from.

**Pull request merged**
